version: "3"

services:
  
    queue:
        image: redis
        ports:
          - 6379:6379
        container_name: queue-redis

    cache:
      image: redis
      ports:
        - 6380:6379
      container_name: cache-redis
  